#SPDX-License-Identifier: MIT-0
---
# tasks file for apt
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade system
  ansible.builtin.apt:
    upgrade: dist

- name: Remove unused packages
  ansible.builtin.apt:
    autoremove: true

- name: Clean apt cache
  ansible.builtin.apt:
    autoclean: true
